---
# SPDX-FileCopyrightText: 2025 The python_openobserve authors
# SPDX-License-Identifier: GPL-3.0-or-later
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    pre_install:
      - pip install mkdocs-material
mkdocs:
  configuration: mkdocs.yml
