---
# SPDX-FileCopyrightText: 2025 The python_openobserve authors
# SPDX-License-Identifier: GPL-3.0-or-later
name: GuardDog

on:
  push:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  guarddog:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    name: Scan dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.13'

      - name: Install dependencies including guarddog
        run: |
          set -x
          sudo apt-get purge -y libgit2-1.7 libgit2-dev
          sudo apt-get install -y heimdal-dev
          curl -OL https://github.com/libgit2/libgit2/archive/refs/tags/v1.9.2.tar.gz && \
            tar xzf v1.9.2.tar.gz && \
            cd libgit2-1.9.2 && \
            ./ci/build.sh && \
            sudo make install
          cd ..
          sudo apt-get install -y libunwind-dev debuginfod libdebuginfod-dev
          pip install -r requirements-dev.txt

      - name: Generate requirements.txt
        run: |
          python3 -mvenv venv
          . venv/bin/activate
          pip install -e .
          pip freeze | grep -v -f requirements-guarddog-ignore.txt | tee requirements.txt

      - name: Check requirements.txt
        run: |
          cat requirements.txt

      - name: Run guarddog
        run: |
          guarddog pypi verify requirements.txt --output-format sarif --exclude-rules repository_integrity_mismatch > guarddog.sarif

      - name: View SARIF file
        run: |
          cat guarddog.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@60168efe1c415ce0f5521ea06d5c2062adbeed1b  # tag=v3.28.17
        with:
          category: guarddog-builtin
          sarif_file: guarddog.sarif
