---
# SPDX-FileCopyrightText: 2025 The python_openobserve authors
# SPDX-License-Identifier: GPL-3.0-or-later
name: precommit

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # tag=v4.2.2

      - name: Install gitleaks
        run: |
          cd /tmp/
          curl -sSfLO https://github.com/gitleaks/gitleaks/releases/download/v8.23.1/gitleaks_8.23.1_linux_x64.tar.gz
          tar xzf gitleaks_*_linux_x64.tar.gz
          sudo install -m 755 gitleaks /usr/local/bin/
        continue-on-error: true
      - name: Install cosign
        uses: sigstore/cosign-installer@3454372f43399081ed03b604cb2d021dabca52bb  # tag=v3.8.2
        with:
          cosign-release: "v2.5.0"
      - name: Install trufflehog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
        continue-on-error: true
      - name: Install mypy
        run: |
          set -x
          pip install -e .[ci]
          pip install -r requirements-dev.txt
          mypy --install-types .
        continue-on-error: true
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # tag=v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure
