---
name: precommit

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Install gitleaks
        run: |
          cd /tmp/
          curl -sSfLO https://github.com/gitleaks/gitleaks/releases/download/v8.23.1/gitleaks_8.23.1_linux_x64.tar.gz
          tar xzf gitleaks_*_linux_x64.tar.gz
          sudo install -m 755 gitleaks /usr/local/bin/
        continue-on-error: true
      - name: Install trufflehog
        run: |
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
        continue-on-error: true
      - name: Install mypy
        run: |
          set -x
          pip install mypy
          mypy --install-types .
        continue-on-error: true
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure
        continue-on-error: true
