---
# SPDX-FileCopyrightText: 2025 The python_openobserve authors
# SPDX-License-Identifier: GPL-3.0-or-later
name: pytest

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.openobserve
      ANSIBLE_SUITE: default-full-python

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache the virtualenv
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt
            ./.venv
          key: ${{ runner.os }}-pyo2-${{ steps.get-date.outputs.date }}

      - name: Environment
        run: |
          set -x
          pwd
          ls
          ls $GITHUB_WORKSPACE
      - name: Install ansible dependencies
        run: |
          pip3 install --require-hashes -r $GITHUB_WORKSPACE/requirements-ansible.txt
          which ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ansible --version
          git clone https://github.com/juju4/ansible-openobserve/ $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
          { echo '[defaults]'; echo 'callback_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Install OpenObserve
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -v molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        continue-on-error: true

      - name: Install dependencies
        run: |
          set -x
          pip install --no-deps -e '.[all]'
          pip install --require-hashes -r requirements-dev.txt

      - name: Set .env for online tests
        run: |
          set -x
          cat > .env <<EOF
          OPENOBSERVE_URL = "http://localhost:5080"
          OPENOBSERVE_USER = "root@example.com"
          OPENOBSERVE_PASS = "root@example.com"
          EOF
          cat .env

      - name: Test with pytest - offline
        run: |
          pytest tests/test_*offline.py --doctest-modules --junitxml=junit/test-${{ matrix.python-version }}-results.xml --cov=com --cov-report=xml --cov-report=html --memray

      - name: Test with pytest  - online
        run: |
          [ -f .env ] && pytest tests/test_openobserve_api.py --doctest-modules --junitxml=junit/test-${{ matrix.python-version }}-results.xml --cov=com --cov-report=xml --cov-report=html --memray
        if: ${{ always() }}
        continue-on-error: true

      - name: Upload pytest test results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # tag=v7.0.1
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-${{ matrix.python-version }}-results.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
