---
# SPDX-FileCopyrightText: 2025 The python_openobserve authors
# SPDX-License-Identifier: GPL-3.0-or-later
name: pytest-uv

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]

    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
      ANSIBLE_EXTRA_VARS: ""
      ANSIBLE_ROLE: juju4.openobserve
      ANSIBLE_SUITE: default-full-python

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache the virtualenv
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
        with:
          path: |
            /var/cache/apt/archives
            /var/lib/apt
            ./.venv
          key: ${{ runner.os }}-pyo2-${{ steps.get-date.outputs.date }}

      - name: Install ansible dependencies
        run: |
          pip3 install -r $GITHUB_WORKSPACE/requirements-ansible.txt
          which ansible
          pip3 show ansible
          ls -l $HOME/.local/bin || true
          ansible --version
          git clone https://github.com/juju4/ansible-openobserve/ $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE
          [ -f molecule/$ANSIBLE_SUITE/requirements.yml ] && ansible-galaxy install -r molecule/$ANSIBLE_SUITE/requirements.yml
          { echo '[defaults]'; echo 'callback_enabled = profile_tasks, timer'; echo 'roles_path = ../:/home/runner/.ansible/roles'; echo 'ansible_python_interpreter: /usr/bin/python3'; } >> ansible.cfg
      - name: Install OpenObserve
        run: |
          cd $GITHUB_WORKSPACE/$ANSIBLE_ROLE && ansible-playbook -i localhost, --connection=local --become -v molecule/$ANSIBLE_SUITE/converge.yml ${ANSIBLE_EXTRA_VARS}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        continue-on-error: true

      - name: Set .env for online tests
        run: |
          set -x
          cat > .env <<EOF
          OPENOBSERVE_URL = "http://localhost:5080"
          OPENOBSERVE_USER = "root@example.com"
          OPENOBSERVE_PASS = "root@example.com"
          EOF
          cat .env

      - name: Install uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Test with pytest - offline
        run: |
          uv run pytest tests/test_*offline.py --doctest-modules --junitxml=junit/test-${{ matrix.python-version }}-results.xml --cov=com --cov-report=xml --cov-report=html --memray

      - name: Test with pytest  - online
        run: |
          [ -f .env ] && uv run pytest tests/test_openobserve_api.py --doctest-modules --junitxml=junit/test-${{ matrix.python-version }}-results.xml --cov=com --cov-report=xml --cov-report=html --memray
        if: ${{ always() }}
        continue-on-error: true
