---
name: Upload Python Package to PyPI Prod

on:
  release:
    types: [created, edited, published, released]
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/python-openobserve/
    permissions:
      id-token: write
    steps:
    # retrieve your distributions here
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build
    - name: Build package
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
